name: H6060 Experiment 1 - Logback

on:
  workflow_dispatch:
    inputs:
      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-deepsource-enabled:
        description: Enable Deepsource scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

      sast-sonarqube-enabled:
        description: Enable SonarQube scan (SAST)
        type: boolean
        required: false
        default: true

      sca-eclipse-steady-enabled:
        description: Enable Eclipse Steady scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build-application:
    name: Build Application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Logback Application - ${{ matrix.os }}
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/java/java-build@main
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: "**/target"
          artifact-name: java-build-${{ matrix.os }}

  create-dependency-tree:
    name: Create Dependency Tree
    needs: build-application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Create Dependency Tree - ${{ matrix.os }}
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/java/java-dependency-tree@main
        with:
          artifact-name: dependency-tree-${{ matrix.os }}

  create-cyclonedx-sbom:
    name: Create CycloneDX Dependency Tree
    needs: build-application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: java-build-${{ matrix.os }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Create CycloneDX SBOM - ${{ matrix.os }}
        uses: seansmith39/H6060-Experiment-Resources/.github/actions/java/java-cyclonedx-sbom@main
        with:
          build-directory: target
          artifact-name: cyclonedx-sbom-java-${{ matrix.os }}

  security_tool_analysis:
    name: Security Tool Analysis
    needs: [ create-dependency-tree, create-cyclonedx-sbom ]
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Perform Security Tool Analysis - ${{ matrix.os }}
        uses: seansmith39/H6060-Experiment-Resources/.github/workflows/experiment-1-java.yml@Run_Experiment_On_Matrix
        with:
            sast-codeql-enabled: ${{ github.event.inputs.sast-codeql-enabled }}
            sast-deepsource-enabled: ${{ github.event.inputs.sast-deepsource-enabled }}
            sast-horusec-enabled: ${{ github.event.inputs.sast-horusec-enabled }}
            sast-semgrep-enabled: ${{ github.event.inputs.sast-semgrep-enabled }}
            sast-snyk-code-enabled: ${{ github.event.inputs.sast-snyk-code-enabled }}
            sast-sonarqube-enabled: ${{ github.event.inputs.sast-sonarqube-enabled }}
            sca-eclipse-steady-enabled: ${{ github.event.inputs.sca-eclipse-steady-enabled }}
            sca-grype-enabled: ${{ github.event.inputs.sca-grype-enabled }}
            sca-owasp-dependency-check-enabled: ${{ github.event.inputs.sca-owasp-dependency-check-enabled }}
            sca-snyk-enabled: ${{ github.event.inputs.sca-snyk-enabled }}
            project-name: H6060-Experiment-1-Logback
            build-artifact: java-build-${{ matrix.os }}
            build-directory: target
